spring:
  application:
    name: dlt-monitor

  kafka:
    template:
      observation-enabled: true    # producer injects trace headers
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: dlt-monitor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      concurrency: 1  # DLT is low volume, 1 thread is enough
      ack-mode: manual
      observation-enabled: true    # consumer extracts trace headers
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    kafka:
      enabled: true

logging:
  level:
    com:
      monitor:
        dltmonitor: DEBUG
  pattern:
    level: "%5p [%d{yyyy-MM-dd HH:mm:ss.SSS}] [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %logger{36} : %msg%n"
