spring:
  application:
    name: email-service

  threads:
    virtual:
      enabled: true


  kafka:
    template:
      observation-enabled: true    # producer injects trace headers
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: email-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.common.event"
        spring.json.value.default.type: "com.common.event.NotificationEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      concurrency: 3
      ack-mode: manual
      observation-enabled: true    # consumer extracts trace headers


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    kafka:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
    metrics:
      export:
        enabled: false

logging:
  level:
    com:
      email:
        emailservice: DEBUG
  pattern:
    level: "%5p [%d{yyyy-MM-dd HH:mm:ss.SSS}] [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %logger{36} : %msg%n"
